name: Selenium Workflow

on:
  workflow_dispatch:
  schedule:
    - cron: '20 13 * * *'  # 15:20 Paris time (UTC+2)

jobs:
  run_selenium:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v3.8
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Selenium Script
      run: python dwnld_rev.py
