name: Selenium Workflow

on:
  schedule:
    - cron: '20 13 * * *'  # 15:20 Paris time (UTC+2)

jobs:
  run_selenium:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Selenium Script
      run: python download_script.py
