name: Selenium Workflow

on:
  workflow_dispatch:


jobs:
  run_selenium:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Update webdriver_manager
      run: pip install --upgrade webdriver_manager 

    - name: Run Selenium Script
      run: python dwnld_rev.py
