name: Selenium Script Execution

on:
  push:
    branches:
      - main

jobs:
  run-selenium-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3.8
        with:
          python-version: 3.8  # Specify your Python version

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Add your requirements if any

      - name: Run Selenium Script
        run: python /Kamalsridharan/p-lauto/blob/main/dwnld_rev.py  # Adjust the path to your script
